#!/usr/bin/env bash

export VISUAL=emacsclient
export EDITOR="$VISUAL"
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

xhost +SI:localuser:$USER
gnome-settings-daemon &
gnome-screensaver &
dunst &
cbatticon &

xset r rate 200 60
xsetroot -cursor_name left_ptr
xsetroot -solid black
setxkbmap -layout us -option ctrl:nocaps
xrdb -merge ~/.Xresources

autokey &
ibus-daemon -r -x -d &
nm-applet &

exec emacs -l ~/.emacs.d/lisp/window-manager.el
