#!/usr/bin/env bash

export VISUAL=emacsclient
export EDITOR="$VISUAL"
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx
export _JAVA_AWT_WM_NONREPARENTING=1

xhost +SI:localuser:$USER
xset r rate 200 60
xsetroot -cursor_name left_ptr
xsetroot -solid black
setxkbmap -layout us -option ctrl:nocaps
xrdb -merge ~/.Xresources

# Run emacs daemon
emacs --daemon &

gnome-settings-daemon &
gnome-screensaver &

# Composite manager
xcompmgr &

# XIM
fcitx &

# Notificaiton Daemon
dunst &

# Network Manager
nm-applet &

# Bluetooth
blueman-applet &

# Caffeine Indicator
caffeine-indicator &

exec stumpwm
