shell_session_update() { :; }

fpath=(~/.zsh_functions $fpath)
autoload -Uz compinit vcs_info && compinit
zstyle ':vcs_info:*' enable git
precmd() { vcs_info }

if [ -d /opt/homebrew ]; then
  export PATH=$PATH:/opt/homebrew/bin
fi

source ~/.zsh.inc/zgen.zsh
source ~/.zsh.inc/alias.sh
source ~/.zsh.inc/gpg-agent.sh
source ~/.zsh.inc/python-pyenv.sh
source ~/.zsh.inc/ruby-rbenv.sh
source ~/.zsh.inc/nodejs-nvm.sh
source ~/.zsh.inc/jvm-sdkman.sh
source ~/.zsh.inc/golang.sh
source ~/.zsh.inc/rust.sh
source ~/.zsh.inc/tmux.sh
source ~/.zsh.inc/emacs.sh

if [ -e ~/.zshrc.machine ]; then
  source ~/.zshrc.machine
fi

setopt prompt_subst
PROMPT_LEAN_TMUX=""

zgen load zsh-users/zsh-autosuggestions
zgen load zsh-users/zsh-syntax-highlighting
zgen load unixorn/tumult.plugin.zsh
zgen load unixorn/warhol.plugin.zsh
zgen load miekg/lean
