check:
	which ruby
	which git

install:
	git clone https://github.com/rbenv/rbenv.git ~/.rbenv
	git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
	./install-ruby.sh

uninstall:
	rm -rf `rbenv root`
